#!/usr/bin/env bash
# Installs and setup haproxy for load balancing

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 97930-web-01 54.144.150.155:80 check
   server 97930-web-02 3.89.155.218:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
