#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# If the number is a multiple of 3 and 5 it displays FizzBuzz
# If it's only a multiple of 3 display Fizz
# If it's only a multiple of 5 display Buzz
# Else display the number

n=1
while ((n <= 100));
do
    if ((n % 3 == 0 && n % 5 == 0))
    then
	echo FizzBuzz
    elif ((n % 3 == 0 && n % 5 != 0))
    then
	echo Fizz
    elif ((n % 3 != 0 && n % 5 == 0))
    then
        echo Buzz
    else
	echo "$n"
	fi
    n=$((n + 1));
done
