#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, and Hi in the nineth loop

n=0
while ((n < 10));
do
    echo Best School;
    if ((n == 8));
    then
	echo Hi
	fi
    n=$((n + 1));
done
